---
abstract: 'Just * Do it: A Catalyst::Plugin::ConfigLoader-style layer over Config::Any'
author:
  - 'Robert Krimen, C<< <rkrimen at cpan.org> >>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.710'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Config-JFDI
no_index:
  directory:
    - inc
    - t
requires:
  Carp::Clan: 0
  Clone: 0
  Config::Any: 0
  Hash::Merge::Simple: 0
  List::MoreUtils: 0
  Moose: 0
  Path::Class: 0
version: 0.01
